//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public int AID { get; set; }
        public string AFirstName { get; set; }
        public string ALastName { get; set; }
        public string AFullName { get; set; }
    }
}
