//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int BID { get; set; }
        public string BISBN { get; set; }
        public string BTitle { get; set; }
    }
}
