//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CID { get; set; }
        public string CFirstName { get; set; }
        public string CLastName { get; set; }
        public string CCardName { get; set; }
    }
}
